symbols:
  - BTCUSDT
  - ETHUSDT
  - BCHUSDT

# 供訓練腳本使用的輸入/輸出路徑
io:
  csv_paths:
    BTCUSDT: resources/btc_15m.csv
    ETHUSDT: resources/eth_15m.csv
    BCHUSDT: resources/bch_15m.csv
  models_dir: models

models:
  use_manifest: true
  manifest_path: models/manifest.json
  globs:
    - "models/*/model.pkl"

realtime:
  require_models: true
  fetch_mode: "csv_only_or_none"
  resources_dir: "resources"

logging:
  level: INFO
  diag: true
