symbols:
  - BTCUSDT
  - ETHUSDT
  - BCHUSDT

# 先用本地 CSV（resources/*_15m.csv）與已訓練模型
fetch:
  mode: csv_only        # csv_only | none | binance
  resources_dir: /opt/crypto_strategy_project/resources

models:
  BTCUSDT:
    dir: /opt/crypto_strategy_project/models/BTCUSDT
  ETHUSDT:
    dir: /opt/crypto_strategy_project/models/ETHUSDT
  BCHUSDT:
    dir: /opt/crypto_strategy_project/models/BCHUSDT

realtime:
  require_models: true
  # 若沒有模型就直接給 no_models_loaded（避免 score=nan）

logging:
  level: INFO
  diag: true
