symbols:
  - BTCUSDT
  - ETHUSDT
  - BCHUSDT

fetch:
  mode: public_binance
  source: binance_public
  base_url: "https://api.binance.com"
  interval: "15m"            # 由程式正規化為 15T
  batch_limit: 500
  max_retries: 3
  retry_sleep_sec: 1.0
  max_backfill_minutes: 360
  writeback_csv: true

train:
  target_horizon_bars: 16
  default_threshold: 0.60

risk:
  atr_n: 14
  pt_atr_mult: 1.0       # 目標 = 1 * ATR
  sl_atr_mult: 0.6       # 停損 = 0.6 * ATR
  fallback_pt_pct: 0.008 # 0.8%
  fallback_sl_pct: 0.005 # 0.5%

runtime:
  require_models: true
  notify:
    telegram: true

realtime:
  allow_stale_one_bar: true

trade:
  mode: signal_only
  fixed_qty: 0.0
  min_notional:
    BTCUSDT: 5.0
    ETHUSDT: 5.0
    BCHUSDT: 5.0

io:
  csv_paths:
    BTCUSDT: resources/btc_15m.csv
    ETHUSDT: resources/eth_15m.csv
    BCHUSDT: resources/bch_15m.csv
  models_dir: models

models:
  use_manifest: true
  manifest_path: models/manifest.json
  globs:
    - "models/*/model.pkl"

resources_dir: resources

execution:
  long_prob_threshold: 0.70
  short_prob_threshold: 0.70
  max_holding_minutes: 240
  atr:
    enabled: false
    h4_col: "atr_h4"
    long:  { tp_mult: 1.5, sl_mult: 1.0 }
    short: { tp_mult: 1.5, sl_mult: 1.0 }

backtest:
  initial_capital: 10000
  risk_per_trade: 0.007
  fee_rate: 0.0004
  slippage: 0.0002

logging:
  level: INFO
  diag: true
