symbols:
  - BTCUSDT
  - ETHUSDT
  - BCHUSDT

# 供訓練腳本使用的輸入/輸出路徑
io:
  csv_paths:
    BTCUSDT: resources/btc_15m.csv
    ETHUSDT: resources/eth_15m.csv
    BCHUSDT: resources/bch_15m.csv
  models_dir: models

# 即時模式下要載入的模型清單
models:
  - name: BTCUSDT
    type: xgboost
    path: models/BTCUSDT/xgb_h16.json
  - name: ETHUSDT
    type: xgboost
    path: models/ETHUSDT/xgb_h16.json
  - name: BCHUSDT
    type: xgboost
    path: models/BCHUSDT/xgb_h16.json

realtime:
  fetch: binance        # binance | csv_only | none
  require_models: true

logging:
  level: INFO
  diag: true
