name: Deploy to GCP VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # （可選）如需先在 CI 跑測試，保留；不需要可移除。
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'

      - name: Install test deps (optional)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          fi

      - name: Start ssh-agent and load key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Sync files to VM via rsync
        run: |
          rsync -az --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.venv' \
            -e "ssh -o StrictHostKeyChecking=yes" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/crypto_strategy_project/

      - name: Run remote deploy script
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash /opt/crypto_strategy_project/deploy.sh"

      # （可選）如果你使用 systemd timer，部署後立刻跑一輪 smoke test
      # - name: Trigger one-shot run (timer-based)
      #   run: |
      #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl start trader-once.service"
