name: Deploy to GCP VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start ssh-agent and load key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_KEY }}

    - name: Add host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

    # ✅ 先建立目錄並賦權給部署用帳號（避免 rsync 23）
    - name: Prepare remote dir
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
          sudo mkdir -p /opt/crypto_strategy_project && \
          sudo chown -R ${USER}:${USER} /opt/crypto_strategy_project \
        "

    # ✅ rsync 不要 --delete，並排除線上產物
    - name: Sync files to VM via rsync (safe)
      run: |
        rsync -az \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='.venv' \
          --exclude='models/**' \
          --exclude='logs/**' \
          --exclude='resources/*.csv' \
          -e "ssh -o StrictHostKeyChecking=yes" \
          ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/crypto_strategy_project/

    # ✅ 用 sudo 跑 deploy.sh，讓 chown 等指令不會因權限失敗
    - name: Run remote deploy script
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo bash /opt/crypto_strategy_project/deploy.sh"
