name: Realtime

on:
  workflow_dispatch:

jobs:
  realtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run realtime with diagnostics
        shell: bash
        continue-on-error: true
        run: |
          mkdir -p logs
          set -o pipefail
          echo "[CI] run_id=${{ github.run_id }} commit=${{ github.sha }}"
          python -V
          python scripts/realtime_loop.py --cfg csp/configs/strategy.yaml --delay-sec 15 2>&1 | tee logs/realtime_${{ github.run_id }}.log
      - name: Upload realtime diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: realtime-diag-${{ github.run_id }}
          path: |
            logs/diag/*.json
            logs/diag/*.npy
            logs/*.log
          if-no-files-found: warn
          retention-days: 7
      - name: Append DIAG to Job Summary
        if: always()
        shell: bash
        run: |
          {
            echo "### Realtime DIAG (tail)"
            echo '```'
            tail -n 200 logs/realtime_${{ github.run_id }}.log || true
            echo '```'
            echo ""
            echo "### NAN Context Files"
            ls -l logs/diag || true
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Grep tz_localize offenders
        if: always()
        shell: bash
        run: |
          {
            echo "### Files containing tz_localize( :"
            grep -RIn --line-number --include="*.py" "tz_localize(" || true
          } >> "$GITHUB_STEP_SUMMARY"
