name: Realtime

on:
  workflow_dispatch:

jobs:
  realtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run realtime prediction with diagnostics
        run: |
          python scripts/predict_and_notify.py --cfg csp/configs/strategy.yaml
        continue-on-error: true
