name: Train & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # 讓 'csp' 成為可匯入套件（I/O 仍在 repo）
          pip install -e . || export PYTHONPATH=$PWD

      - name: Train models (BTCUSDT/ETHUSDT/BCHUSDT)
        env:
          CSP_TRAIN_SYMBOLS: "BTCUSDT,ETHUSDT,BCHUSDT"
          CSP_TRAIN_OUTDIR: "models"
          CSP_OPTIMIZE: "false"
          CSP_OPT_N_TRIALS: "60"
          CSP_OPT_TIMEOUT_MIN: "25"
        run: |
          set -euo pipefail
          python scripts/train_multi.py \
            --symbols "$CSP_TRAIN_SYMBOLS" \
            --out-dir "$CSP_TRAIN_OUTDIR" \
            --cfg csp/configs/strategy.yaml \
            $([ "${CSP_OPTIMIZE}" = "true" ] && echo --optimize || true)
          echo "[CI] models tree:"
          find models -maxdepth 2 -type f | sort
          test -s models/manifest.json

      - name: Upload models artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-models
          path: models/

  backtest:
    runs-on: ubuntu-latest
    needs: [train]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e . || export PYTHONPATH=$PWD

      - name: Download trained models
        uses: actions/download-artifact@v4
        with:
          name: trained-models
          path: models/

      - name: Backtest (always update to latest via --fetch inc)
        run: |
          set -euo pipefail
          python scripts/backtest_multi.py \
            --cfg csp/configs/strategy.yaml \
            --days 30 \
            --fetch inc \
            --save-summary --out-dir reports --format both
          echo "[CI] reports tree:"
          find reports -type f | sort || true

      - name: Upload reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: backtest-reports
          path: reports/

  deploy:
    runs-on: ubuntu-latest
    needs: [backtest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download trained models
        uses: actions/download-artifact@v4
        with:
          name: trained-models
          path: models/

      - name: Show models
        run: |
          echo "[CI] models tree after download:"
          find models -maxdepth 2 -type f | sort
          test -s models/manifest.json

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync code + models to VM
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          set -euo pipefail
          RSYNC_FLAGS="-avz --delete --exclude .git --exclude .github"
          rsync $RSYNC_FLAGS ./ "${SSH_USER}@${SSH_HOST}:/home/${SSH_USER}/repo_tmp/"

      - name: Deploy to VM (sync + env + systemd)
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          GIT_SHA: ${{ github.sha }}
        run: |
          set -euo pipefail
          ssh -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" \
            TELEGRAM_BOT_TOKEN='${{ secrets.TELEGRAM_BOT_TOKEN }}' \
            TELEGRAM_CHAT_ID='${{ secrets.TELEGRAM_CHAT_ID }}' \
            GIT_SHA="$GIT_SHA" \
            bash -euo pipefail -s <<'REMOTE'
          set -euo pipefail
          SRC="/home/$USER/repo_tmp"
          DST="/opt/crypto_strategy_project"

          echo "[DEPLOY] Sync code (including models/) to ${DST}"
          sudo -n rsync -a --delete "${SRC}/" "${DST}/"

          echo "[DEPLOY] Ensure venv"
          if [ ! -x "${DST}/.venv/bin/python" ]; then
            sudo -n python3 -m venv "${DST}/.venv"
          fi
          sudo -n bash -lc "${DST}/.venv/bin/pip install --upgrade pip && \
                            [ -f ${DST}/requirements.txt ] && ${DST}/.venv/bin/pip install -r ${DST}/requirements.txt || true"

          echo "[DEPLOY] Provision env for systemd (/etc/crypto_strategy_project.env)"
          sudo -n install -m 600 -o root -g root /dev/null /etc/crypto_strategy_project.env
          printf "TELEGRAM_BOT_TOKEN=%s\nTELEGRAM_CHAT_ID=%s\n" \
            "$TELEGRAM_BOT_TOKEN" "$TELEGRAM_CHAT_ID" | sudo -n tee /etc/crypto_strategy_project.env >/dev/null
          sudo -n awk -F= '/^TELEGRAM_(BOT_TOKEN|CHAT_ID)=/ {printf("[CHECK] %s present len=%d\n",$1,length($2))}' /etc/crypto_strategy_project.env
          sudo -n chown root:root /etc/crypto_strategy_project.env
          sudo -n chmod 600 /etc/crypto_strategy_project.env

          if ! sudo -n bash -lc "grep -q '^TELEGRAM_BOT_TOKEN=' /etc/crypto_strategy_project.env && \
                                 grep -q '^TELEGRAM_CHAT_ID='   /etc/crypto_strategy_project.env"; then
            echo "::error::missing TELEGRAM env in /etc/crypto_strategy_project.env"
            exit 1
          fi

          echo "[DEPLOY] Install systemd units"
          sudo -n cp "${DST}/systemd/trader-once.service" /etc/systemd/system/trader-once.service
          sudo -n cp "${DST}/systemd/trader-once.timer"   /etc/systemd/system/trader-once.timer
          if [ -d /etc/systemd/system/trader-once.service.d ]; then
            echo "[DEPLOY] Cleanup broken drop-in override"
            sudo -n rm -f /etc/systemd/system/trader-once.service.d/override.conf || true
          fi

          echo "[DEPLOY] Reload & (re)start timer/service"
          sudo -n systemctl daemon-reload
          sudo -n systemctl enable --now trader-once.timer
          sudo -n systemctl restart trader-once.timer
          sudo -n systemctl stop trader-once.service || true
          if ! sudo -n systemctl start trader-once.service ; then
            echo "::warning::trader-once.service failed to start, dumping logs"
            sudo -n systemctl status trader-once.service --no-pager || true
            sudo -n journalctl -xeu trader-once.service --no-pager -n 200 || true
            exit 1
          fi

          echo "[DEPLOY] systemctl status"
          sudo -n systemctl status trader-once.timer --no-pager
          sudo -n systemctl status trader-once.service --no-pager || true
          REMOTE
