name: Train & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Train models (BTCUSDT/ETHUSDT/BCHUSDT)
        env:
          CSP_TRAIN_SYMBOLS: "BTCUSDT,ETHUSDT,BCHUSDT"
          CSP_TRAIN_OUTDIR: "models"
        run: |
          set -euo pipefail
          python scripts/train_multi.py \
            --symbols "$CSP_TRAIN_SYMBOLS" \
            --out-dir "$CSP_TRAIN_OUTDIR" \
            --cfg csp/configs/strategy.yaml
          echo "[CI] models tree:"
          find models -maxdepth 2 -type f | sort
          test -s models/manifest.json

      - name: Upload models artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-models
          path: models/

  deploy:
    runs-on: ubuntu-latest
    needs: [train]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download trained models
        uses: actions/download-artifact@v4
        with:
          name: trained-models
          path: models/

      - name: Show models
        run: |
          echo "[CI] models tree after download:"
          find models -maxdepth 2 -type f | sort
          test -s models/manifest.json

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync code + models to VM
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          set -euo pipefail
          RSYNC_FLAGS="-avz --delete --exclude .git --exclude .github"
          rsync $RSYNC_FLAGS ./ "${SSH_USER}@${SSH_HOST}:/home/${SSH_USER}/repo_tmp/"

      - name: Install to /opt + systemd reload + run-once (on VM)
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          set -euo pipefail
          ssh -o StrictHostKeyChecking=yes "${SSH_USER}@${SSH_HOST}" 'bash -s' <<'REMOTE'
          set -euo pipefail
          SRC="/home/$USER/repo_tmp"
          DST="/opt/crypto_strategy_project"

          echo "[DEPLOY] Sync code (including models/) to ${DST}"
          sudo -n rsync -a --delete "${SRC}/" "${DST}/"

          echo "[DEPLOY] Ensure venv"
          if [ ! -x "${DST}/.venv/bin/python" ]; then
            sudo -n python3 -m venv "${DST}/.venv"
          fi
          sudo -n bash -lc "${DST}/.venv/bin/pip install --upgrade pip && \
                            [ -f ${DST}/requirements.txt ] && ${DST}/.venv/bin/pip install -r ${DST}/requirements.txt || true"

          echo "[DEPLOY] Install systemd units"
          sudo -n cp "${DST}/systemd/trader-once.service" /etc/systemd/system/trader-once.service
          sudo -n cp "${DST}/systemd/trader-once.timer"   /etc/systemd/system/trader-once.timer
          sudo -n systemctl daemon-reload
          sudo -n systemctl enable --now trader-once.timer
          # 確保任何 timer 變更都即時套用（冪等）
          sudo -n systemctl restart trader-once.timer
          sudo -n systemctl stop trader-once.service || true

          echo "[DEPLOY] One-shot run"
          sudo -n systemctl start trader-once.service

          echo "[DEPLOY] Status"
          sudo -n systemctl status trader-once.timer   --no-pager || true
          sudo -n systemctl status trader-once.service --no-pager || true
          # 額外可觀察點：下一次觸發時間（便於在 CI log 中確認排程）
          sudo -n systemctl list-timers --all | grep -i trader-once || true

          echo "== recent journal (last 200 lines, last 30 minutes) =="
          if ! sudo -n journalctl -u trader-once.service --since "-30 min" -o cat | tail -n 200 ; then
            sudo -n journalctl -u trader-once.service -n 200 -o cat || true
          fi

          echo "== models on VM =="
          sudo -n bash -lc "find ${DST}/models -maxdepth 2 -type f | sort || true"
          REMOTE
